# Pick whichever you actually use. Comment out the rest.
github: [Abbasi-Alain]
# patreon: <username>
# open_collective: <slug>
# ko_fi: <username>
# tidelift: <platform>/<package>
# custom: ["https://your-funding-url"]
